### PR TITLE
Minor bug fixes

### PR DESCRIPTION
**Pull request by peitschie**
Thanks for this fork! It's nice to see some activity around this again.
I've just fixed two minor issues that blocked me from running this extension with my local setup (karma+jasmine+webpack).

I'm happy to rework them in any way you see fit 😃

### CODE REVIEW

**Comment by lucono** [comment]
Thanks for the PR, @peitschie. You mind [opening bug issues](https://github.com/lucono/karma-test-explorer/issues/new/choose) for these two and providing the debug logs and as much other information as possible in the bug template - such as your operating system where this bug occurs. Command argument quoting and/or escaping has different rules on different operating systems and can easily work on one and break on another, being very error-prone. With the logs, it'll be easier to test and validate the fix for other platforms as well. Thanks.

**Comment by peitschie** [comment]
No worries at all. Can appreciate how complex multi-platform escaping is. I've tried to target the patch in a way that it will never make things worse, but I haven't really tried hard on OSX/Linux, as I know there are a lot more characters that can make their ways into paths on those systems.

**Comment by peitschie** [comment]
I've raised https://github.com/lucono/karma-test-explorer/issues/9 for the spaces-in-paths issue, and https://github.com/lucono/karma-test-explorer/issues/10 for the `clearContext` change.

For the client context tweak however, I'm unable to find a reproduction case I can share publicly, unfortunately. I've been through my tests with a fine-tooth comb and found no issues. I've even tried stripping down the whole suite to practically nothing, and still this error turns up.

As best as I can guess, it might be connected with https://github.com/karma-runner/karma/issues/3482. Updating to karma 6 solves the issue, but for various reasons this isn't something I can do for the repo at this stage.

I had a search through your own changes here, and could discover any reason why the `clearContext` is being forced as a mandatory setting. Turning it off fixes the issue... but I don't really know the wider impacts of this tweak.

**Comment by lucono** [comment]
@peitschie Thanks for filing the issues. The fix for issue #10 looks good, and I'll merge it if you can split out the proposed fixes for #9 into a different PR. I will look into the Mac/Linux part to make sure that the file path space issue can be resolved for all of the platforms after which I'll publish both fixes to the marketplace. Thanks.

**Comment by peitschie** [comment]
Apologies for the delay here @lucono ... it's been a long weekend for most in my country 😃 
Do you still want me to do the above splitting of the PRs?

**Comment by lucono** [comment]
No worries @peitschie. I've included your proposed change for `client.clearContext` in PR #11, so we should be good. For the filename space issue, I've implemented a different approach that bypasses the shell and delegates directly to the OS to handle any quoting and escaping, which should work across Windows and Mac/Linux while avoiding error-prone manual quoting/escaping. If you don't mind testing with the `beta` branch to verify if it resolves the space issue for you on Windows, I will publish it to the marketplace.

You can build it locally with `npm run validate`, and then manually [install](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) the `.vsix` file that's generated in the project root. It should show up as `v0.3.0`. Thanks.

**Comment by peitschie** [comment]
Superseded by #11 🎉

**Pull request closed without merging**
